# Properties
  name              : "Dragon"
  mass              : 100.0                   #kg
  inertia           : [100.0, 50.0, 25.0]     #kg*m^2
  model             : "Models/Dragon.stl"
  colorscale        : "Oranges"
  model_axis_order  : [2, 0, 1]
  nav_red           : [.33, 0.105, 0]
  nav_green         : [.33, -0.11, 0]
  control:
    orient_control_kp : 7.0
    orient_control_kd : 35
  star_tracker:
    body_to_boresight : [-0.70710678118, 0, 0, 0.70710678118]
