sim:
  central_body  : "Earth"
  t0            : 2024-04-08T18:18:00 #sec
  tf            : 5580                #sec
  dt            : 1                   #sec
  save_loc      : "output"
  save_file     : "sim.npy"

satellites:
  dragon:
    vehicle_conf: "Config/Vehicles/Dragon.yaml"
    # Initial conditions
    keplerian:
      alt       : 423000              #m
      ecc       : 0.00
      inc       : 51.6                #deg
      lan       : 0.0                 #deg
      argp      : 0.0                 #deg
      TA        : 0.0                 #deg
    q_body_to_inertial  : [1, 0, 0, 0]
    omega_body          : [0, 0, 0]   #rad/s
  